### ISSUE TITLE
Missing information.

### ISSUE THREAD

**Issue by VladimirWebDev** [Way2CU/Saffron-New-Site#1]
- [x] Site title.
- [x] Text "Start your franchise now!" looks like button. If it is what is behaviour.?
![image](https://user-images.githubusercontent.com/25882157/29494986-ea19f14a-85b5-11e7-8043-0c8ab076b578.png)
- [x] Font Family (Like on previous version of Saffron site..?)
- [x] Gallery for food samples, should it have lightbox.?
![image](https://user-images.githubusercontent.com/25882157/29495001-3cddbb32-85b6-11e7-8c56-427ecb9b8557.png)

**Comment by talovdat** [comment]
Sent the guy 2 emails. 
Waiting for response.

**Comment by talovdat** [comment]
Site title - **Saffron**

Text "Start your franchise now!" looks like button. If it is what is behaviour.? -  **It's a button, when clicking on it, it scrolls you down to the contact form**

Font Family (Like on previous version of Saffron site..?) - **Yes.**

 Gallery for food samples, should it have lightbox.? - **All images needs to be replaced, new images will be sent via email. It shouldn't have a lightbox. The gallery needs to be scrollable from side to side.**
